baseURL = 'https://senior-project-modular-synthesizer.github.io/Hugo-Website/'
languageCode = 'en-us'
title = 'Seven Deadly Synths'
theme = 're-terminal'
relativeURLs = true
[params]
    themeColor = "green"

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Seven Deadly Synths"
    [languages.en.params.logo]
      logoText = "Seven Deadly Synths"
      logoHomeLink = "https://github.com/Senior-Project-Modular-Synthesizer/SynthCodeESPIDF"

[markup.goldmark.parser.attribute]
  block = true
  title = true