baseURL = 'https://senior-project-modular-synthesizer.github.io/Hugo-Website/'
languageCode = 'en-us'
title = 'Unnamed Synth'
theme = 're-terminal'

[params]
    themeColor = "green"

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Unnamed Synth"
    [languages.en.params.logo]
      logoText = "Seven Deadly Synths"
      logoHomeLink = "/"

[markup.goldmark.parser.attribute]
  block = true
  title = true